import { useEffect, useRef, type ReactNode } from 'react';
import type { ItemStatus, Platform, Provenance } from '../lib/types';
import { PLATFORM_META, STATUS_META } from '../lib/platforms';
import { cx, fmtDateTime } from '../lib/util';
import { IconLock, IconSpark, IconX } from './Icons';

export function PlatformBadge({ platform, compact }: { platform: Platform | 'all'; compact?: boolean }) {
  if (platform === 'all') return <span className="badge badge-all">All channels</span>;
  const m = PLATFORM_META[platform];
  return (
    <span className={cx('badge', `badge-${platform}`)} title={m.label}>
      <span className="badge-dot" aria-hidden="true" />
      {compact ? m.short : m.label}
    </span>
  );
}

export function StatusPill({ status }: { status: ItemStatus }) {
  return (
    <span className={cx('status', `status-${status}`)} title={STATUS_META[status].hint}>
      {STATUS_META[status].label}
    </span>
  );
}

export function AiLabel({ provenance }: { provenance: Provenance | null | undefined }) {
  if (!provenance) return null;
  const title = `Generated by ${provenance.generated_by}${provenance.agents.length ? ` with ${provenance.agents.join(', ')}` : ''} · ${provenance.model} · ${fmtDateTime(provenance.generated_at)}`;
  return (
    <span className="ai-label" title={title}>
      <IconSpark width={14} height={14} />
      {provenance.mode === 'demo' ? 'AI draft (demo template)' : 'AI-generated'}
      {provenance.edited_by_user ? ' · edited' : ''}
    </span>
  );
}

export function InternalPlanNote() {
  return (
    <span className="internal-note" title="Planned dates are internal records. Nothing is scheduled or published on any social platform.">
      <IconLock width={13} height={13} /> Internal plan only
    </span>
  );
}

export function Empty({ title, children, action }: { title: string; children?: ReactNode; action?: ReactNode }) {
  return (
    <div className="empty">
      <h3>{title}</h3>
      {children && <p>{children}</p>}
      {action}
    </div>
  );
}

export function Spinner({ label = 'Loading' }: { label?: string }) {
  return <span className="spinner" role="status" aria-label={label} />;
}

export function Modal({ title, onClose, children, footer, wide }: { title: string; onClose: () => void; children: ReactNode; footer?: ReactNode; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const prev = document.activeElement as HTMLElement | null;
    ref.current?.querySelector<HTMLElement>('input, textarea, select, button:not(.modal-x)')?.focus();
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'Tab' && ref.current) {
        const f = [...ref.current.querySelectorAll<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')].filter((el) => !el.hasAttribute('disabled'));
        if (!f.length) return;
        if (e.shiftKey && document.activeElement === f[0]) {
          e.preventDefault();
          f[f.length - 1].focus();
        } else if (!e.shiftKey && document.activeElement === f[f.length - 1]) {
          e.preventDefault();
          f[0].focus();
        }
      }
    };
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('keydown', onKey);
      prev?.focus?.();
    };
  }, [onClose]);
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className={cx('modal', wide && 'modal-wide')} role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={ref}>
        <header className="modal-head">
          <h2 id="modal-title">{title}</h2>
          <button className="icon-btn modal-x" onClick={onClose} aria-label="Close dialog">
            <IconX />
          </button>
        </header>
        <div className="modal-body">{children}</div>
        {footer && <footer className="modal-foot">{footer}</footer>}
      </div>
    </div>
  );
}

export function Confirm({
  title,
  body,
  confirmLabel,
  onConfirm,
  onCancel,
  danger = true,
}: {
  title: string;
  body: ReactNode;
  confirmLabel: string;
  onConfirm: () => void;
  onCancel: () => void;
  danger?: boolean;
}) {
  return (
    <Modal
      title={title}
      onClose={onCancel}
      footer={
        <>
          <button className="btn btn-ghost" onClick={onCancel}>
            Cancel
          </button>
          <button className={cx('btn', danger ? 'btn-danger' : 'btn-primary')} onClick={onConfirm}>
            {confirmLabel}
          </button>
        </>
      }
    >
      <div className="confirm-body">{body}</div>
    </Modal>
  );
}

export function Field({ label, hint, children, id }: { label: string; hint?: string; children: ReactNode; id: string }) {
  return (
    <div className="field">
      <label htmlFor={id}>{label}</label>
      {children}
      {hint && (
        <small className="hint" id={`${id}-hint`}>
          {hint}
        </small>
      )}
    </div>
  );
}

export function PageHeader({ title, subtitle, actions }: { title: string; subtitle?: ReactNode; actions?: ReactNode }) {
  return (
    <div className="page-head">
      <div>
        <h1>{title}</h1>
        {subtitle && <p className="muted">{subtitle}</p>}
      </div>
      {actions && <div className="page-actions">{actions}</div>}
    </div>
  );
}

export function Segmented<T extends string>({ value, options, onChange, label }: { value: T; options: { value: T; label: string }[]; onChange: (v: T) => void; label: string }) {
  return (
    <div className="segmented" role="group" aria-label={label}>
      {options.map((o) => (
        <button key={o.value} className={cx('seg', value === o.value && 'seg-on')} aria-pressed={value === o.value} onClick={() => onChange(o.value)}>
          {o.label}
        </button>
      ))}
    </div>
  );
}

export function ChipToggle({ on, onClick, children, label }: { on: boolean; onClick: () => void; children: ReactNode; label?: string }) {
  return (
    <button className={cx('chip', on && 'chip-on')} aria-pressed={on} onClick={onClick} aria-label={label}>
      {children}
    </button>
  );
}
